# Generated by Django 6.1.1 on 2026-09-10 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_area', models.CharField(choices=[('MATH', 'Mathematics'), ('ENG', 'English'), ('KIS', 'Kiswahili'), ('SCI', 'Science & Technology'), ('SST', 'Social Studies'), ('CRE', 'Christian Religious Education'), ('CA', 'Creative Arts'), ('AGR', 'Agriculture')], max_length=10)),
                ('strand', models.CharField(max_length=150)),
                ('sub_strand', models.CharField(blank=True, max_length=150)),
                ('mastery_level', models.CharField(choices=[('EE', 'Exceeds Expectation'), ('ME', 'Meets Expectation'), ('AE', 'Approaches Expectation'), ('BE', 'Below Expectation')], max_length=2)),
                ('assessed_on', models.DateField()),
                ('teacher_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.student')),
            ],
            options={
                'ordering': ['-assessed_on'],
            },
        ),
    ]
