# Generated by Django 5.2.6 on 2026-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_feepayment_options_alter_feepayment_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
