# Generated by Django 5.2.6 on 2026-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_feepayment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Administrator'), ('ADMIN', 'School Administrator'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('STUDENT', 'Student')], default='TEACHER', max_length=20),
        ),
    ]
